import {
  ServiceCategory,
  WorkerProfile,
  ServiceRequest,
  AuditLog,
} from "../types";

export const INITIAL_CATEGORIES: ServiceCategory[] = [
  {
    id: "plumbing",
    name: "Plumbing Repairs",
    hindiName: "नल-प्लंबिंग सेवा",
    iconName: "Wrench",
    description: "Fix leaks, pipe installations, bathroom fitting repairs, and drainage unclogging by certified plumbers.",
    subServices: ["Pipe Leak Repair", "Tap Installation", "P-Trap Replacement", "Drain Unclogging"],
    basePrice: 350,
  },
  {
    id: "electrical",
    name: "Electrical Wiring & Appliances",
    hindiName: "बिजली और उपकरण",
    iconName: "Zap",
    description: "Circuit breaker fixes, ceiling fan installation, short circuit diagnosis, and safety inspections.",
    subServices: ["Fan Installation", "MCB Tripping Fix", "Switchboard Repair", "Wiring Inspection"],
    basePrice: 400,
  },
  {
    id: "cleaning",
    name: "Deep House Cleaning",
    hindiName: "घर की गहरी सफाई",
    iconName: "Sparkles",
    description: "Full house deep cleaning, bathroom sanitation, kitchen degreasing, and sofa shampooing.",
    subServices: ["2BHK Deep Clean", "Kitchen Sanitation", "Bathroom Scrubbing", "Sofa Shampooing"],
    basePrice: 800,
  },
  {
    id: "painting",
    name: "Wall Painting & Touch-up",
    hindiName: "दीवार पुताई व पेंट",
    iconName: "Paintbrush",
    description: "Interior wall touch-ups, waterproof coating, dampness treatment, and full room painting.",
    subServices: ["Wall Touch-up", "Dampness Treatment", "Waterproof Paint", "Color Coating"],
    basePrice: 600,
  },
  {
    id: "carpentry",
    name: "Furniture Repair & Carpentry",
    hindiName: "बढ़ईगीरी व फर्नीचर",
    iconName: "Hammer",
    description: "Door hinge alignment, cabinet repairs, custom wood fitting, and lock installations.",
    subServices: ["Hinge Alignment", "Cabinet Repair", "Lock Installation", "Wood Polishing"],
    basePrice: 450,
  },
  {
    id: "ac-repair",
    name: "AC & Appliance Repair",
    hindiName: "एसी व उपकरण मरम्मत",
    iconName: "Wrench",
    description: "AC servicing, gas charging, refrigerator repair, and appliance troubleshooting.",
    subServices: ["AC Servicing", "Gas Charging", "Appliance Maintenance", "Compressor Check"],
    basePrice: 500,
  },
];

export const INITIAL_WORKERS: WorkerProfile[] = [
  {
    id: "worker-1",
    workerCode: "W-001",
    name: "Suresh Kumar",
    phone: "+91 98201 45231",
    societyName: "Shivaji Labour Cooperative Society",
    rating: 4.8,
    jobsCompleted: 45,
    skills: ["Plumbing", "Pipe Fitting"],
    serviceAreas: ["Thane", "Kalwa"],
    status: "AVAILABLE",
    availableNow: true,
  },
  {
    id: "worker-2",
    workerCode: "W-002",
    name: "Ramesh Patil",
    phone: "+91 97654 31872",
    societyName: "Thane Skilled Workers Cooperative",
    rating: 4.6,
    jobsCompleted: 38,
    skills: ["Electrical", "Wiring", "Fan Repair"],
    serviceAreas: ["Thane", "Majiwada"],
    status: "BUSY",
    availableNow: false,
  },
  {
    id: "worker-3",
    workerCode: "W-003",
    name: "Amit Yadav",
    phone: "+91 98765 21430",
    societyName: "Maharashtra Service Workers Society",
    rating: 4.7,
    jobsCompleted: 52,
    skills: ["Carpentry", "Furniture Repair"],
    serviceAreas: ["Kalwa", "Mumbra"],
    status: "AVAILABLE",
    availableNow: true,
  },
  {
    id: "worker-4",
    workerCode: "W-004",
    name: "Mahesh Shinde",
    phone: "+91 98192 67345",
    societyName: "Shivaji Labour Cooperative Society",
    rating: 4.5,
    jobsCompleted: 29,
    skills: ["Painting", "Wall Repair"],
    serviceAreas: ["Thane", "Wagle Estate"],
    status: "AVAILABLE",
    availableNow: true,
  },
  {
    id: "worker-5",
    workerCode: "W-005",
    name: "Imran Shaikh",
    phone: "+91 99876 54123",
    societyName: "Thane General Workers Cooperative",
    rating: 4.9,
    jobsCompleted: 64,
    skills: ["Plumbing", "Drain Unclogging", "Tap Fitting"],
    serviceAreas: ["Thane", "Kalher", "Bhiwandi"],
    status: "BUSY",
    availableNow: false,
  },
  {
    id: "worker-6",
    workerCode: "W-006",
    name: "Vijay More",
    phone: "+91 97021 86452",
    societyName: "Maharashtra Skilled Labour Society",
    rating: 4.4,
    jobsCompleted: 22,
    skills: ["AC Repair", "Appliance Repair"],
    serviceAreas: ["Thane", "Kopri", "Naupada"],
    status: "AVAILABLE",
    availableNow: true,
  },
];

export const INITIAL_REQUESTS: ServiceRequest[] = [];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
