import { ServiceCategory, WorkerProfile, ServiceRequest, AuditLog } from "../types";

export const INITIAL_CATEGORIES: ServiceCategory[] = [
  {
    id: "plumbing",
    name: "Plumbing",
    hindiName: "प्लंबिंग",
    iconName: "Wrench",
    description: "Pipe repair, leakage fixing, tap & sink installation, drainage",
    subServices: ["Pipe repair", "Drainage clearing", "Tap installation", "Water heater connection"],
    workerCount: 24,
    photoRequirement: "OPTIONAL",
    basePrice: 450,
  },
  {
    id: "electrical",
    name: "Electrical",
    hindiName: "इलेक्ट्रिकल",
    iconName: "Zap",
    description: "MCB tripping, wiring repair, fan/light installation, socket repair",
    subServices: ["MCB repair", "Short circuit fix", "Wiring & Switches", "Appliance connection"],
    workerCount: 18,
    photoRequirement: "REQUIRED",
    basePrice: 500,
  },
  {
    id: "carpentry",
    name: "Carpentry",
    hindiName: "बढ़ईगीरी",
    iconName: "Hammer",
    description: "Furniture repair, door/window latch fixing, cabinet assembly",
    subServices: ["Door hinge fix", "Furniture assembly", "Cabinet repair", "Lock installation"],
    workerCount: 12,
    photoRequirement: "OPTIONAL",
    basePrice: 600,
  },
  {
    id: "painting",
    name: "Painting",
    hindiName: "पेंटिंग",
    iconName: "Paintbrush",
    description: "Wall touch-up, full room painting, waterproofing, damp repair",
    subServices: ["Wall touch-up", "Waterproofing coat", "Interior painting", "Door painting"],
    workerCount: 31,
    photoRequirement: "REQUIRED",
    basePrice: 800,
  },
  {
    id: "cleaning",
    name: "Deep Cleaning",
    hindiName: "सफाई",
    iconName: "Sparkles",
    description: "Kitchen deep clean, bathroom sanitization, sofa cleaning",
    subServices: ["Kitchen cleaning", "Bathroom sanitization", "Water tank cleaning", "Sofa wash"],
    workerCount: 45,
    photoRequirement: "NOT_REQUIRED",
    basePrice: 700,
  },
  {
    id: "gardening",
    name: "Gardening",
    hindiName: "बागवानी",
    iconName: "Flower2",
    description: "Lawn trimming, plant pruning, soil fertilization, garden setup",
    subServices: ["Lawn mowing", "Plant pruning", "Pest spray", "Potting & soil change"],
    workerCount: 9,
    photoRequirement: "OPTIONAL",
    basePrice: 400,
  },
  {
    id: "driving",
    name: "Driver on Demand",
    hindiName: "ड्राइवर",
    iconName: "Car",
    description: "Temporary personal driver for city travel or outstation trips",
    subServices: ["City daily commute", "Outstation trip", "Commercial vehicle driving"],
    workerCount: 22,
    photoRequirement: "NOT_REQUIRED",
    basePrice: 650,
  },
  {
    id: "appliance",
    name: "Appliance Repair",
    hindiName: "उपकरण मरम्मत",
    iconName: "Tv",
    description: "AC servicing, washing machine repair, refrigerator cooling fix",
    subServices: ["AC gas refill", "Washing machine repair", "Fridge cooling fix", "Microwave repair"],
    workerCount: 16,
    photoRequirement: "OPTIONAL",
    basePrice: 550,
  },
];

export const INITIAL_WORKERS: WorkerProfile[] = [
  {
    id: "worker-1",
    workerCode: "W-041",
    name: "Ramesh Sharma",
    phone: "+91 98765 43210",
    societyName: "Shivaji Labour Cooperative Society",
    federationName: "Mumbai Suburban Labour Federation",
    verificationStatus: "VERIFIED",
    isAvailable: true,
    rating: 4.8,
    jobsCompleted: 32,
    skills: ["Plumbing", "Pipe repair", "Drainage"],
    serviceAreas: ["Borivali East", "Kandivali West", "Malad"],
  },
  {
    id: "worker-2",
    workerCode: "W-058",
    name: "Suresh Patil",
    phone: "+91 98123 45678",
    societyName: "Ekta Labour Cooperative Society",
    federationName: "Thane District Labour Federation",
    verificationStatus: "VERIFIED",
    isAvailable: true,
    rating: 4.9,
    jobsCompleted: 48,
    skills: ["Electrical", "MCB repair", "Wiring"],
    serviceAreas: ["Borivali East", "Thane West", "Dahisar"],
  },
  {
    id: "worker-3",
    workerCode: "W-012",
    name: "Anil Kamble",
    phone: "+91 97654 32109",
    societyName: "Jai Hind Workers Cooperative",
    federationName: "Mumbai Suburban Labour Federation",
    verificationStatus: "VERIFIED",
    isAvailable: true,
    rating: 4.7,
    jobsCompleted: 19,
    skills: ["Carpentry", "Furniture repair", "Lock installation"],
    serviceAreas: ["Andheri East", "Borivali East", "Goregaon"],
  },
  {
    id: "worker-4",
    workerCode: "W-089",
    name: "Sunita Yadav",
    phone: "+91 99887 76655",
    societyName: "Mahila Self-Help Labour Cooperative",
    federationName: "Mumbai Suburban Labour Federation",
    verificationStatus: "VERIFIED",
    isAvailable: false,
    rating: 5.0,
    jobsCompleted: 64,
    skills: ["Deep Cleaning", "Kitchen cleaning", "Bathroom sanitization"],
    serviceAreas: ["Borivali East", "Bandra West", "Juhu"],
  },
];

export const INITIAL_REQUESTS: ServiceRequest[] = [
  {
    id: "REQ-1001",
    consumerId: "cons-1",
    consumerName: "Priya Verma",
    consumerPhone: "+91 98200 11223",
    categoryId: "electrical",
    categoryName: "Electrical",
    title: "MCB tripping repeatedly in main hall",
    problemDescription: "The main circuit breaker trips whenever the AC and refrigerator are turned on simultaneously. Need urgent inspection.",
    preferredDate: "2026-08-29",
    preferredTimeSlot: "Morning (8am – 12pm)",
    address: {
      houseNo: "Flat 402, Gokul Dham Heights",
      locality: "Borivali East",
      pinCode: "400066",
      city: "Mumbai",
    },
    urgent: true,
    status: "UNDER_REVIEW",
    createdAt: "2026-08-28 09:30 AM",
    timeline: [
      {
        status: "REQUESTED",
        label: "Request Submitted",
        timestamp: "2026-08-28 09:30 AM",
        description: "Submitted by Priya Verma",
      },
      {
        status: "UNDER_REVIEW",
        label: "Admin Reviewing",
        timestamp: "2026-08-28 09:35 AM",
        description: "Cooperative Admin is verifying details and candidate workers",
      },
    ],
    amount: {
      base: 500,
      serviceFee: 50,
      gst: 99,
      total: 649,
    },
  },
  {
    id: "REQ-1002",
    consumerId: "cons-2",
    consumerName: "Amitabh Roy",
    consumerPhone: "+91 97111 22334",
    categoryId: "plumbing",
    categoryName: "Plumbing",
    title: "Kitchen sink drain leakage",
    problemDescription: "Water dripping under the cabinet from the waste pipe connection. Needs replacement P-trap.",
    preferredDate: "2026-08-28",
    preferredTimeSlot: "Afternoon (12pm – 4pm)",
    address: {
      houseNo: "B-12, Green Acres Society",
      locality: "Kandivali West",
      pinCode: "400067",
      city: "Mumbai",
    },
    urgent: false,
    status: "WORKER_ASSIGNED",
    assignedWorkerId: "worker-1",
    assignedWorkerName: "Ramesh Sharma",
    createdAt: "2026-08-28 08:00 AM",
    timeline: [
      {
        status: "REQUESTED",
        label: "Request Submitted",
        timestamp: "2026-08-28 08:00 AM",
      },
      {
        status: "UNDER_REVIEW",
        label: "Admin Reviewing",
        timestamp: "2026-08-28 08:15 AM",
      },
      {
        status: "WORKER_ASSIGNED",
        label: "Worker Assigned",
        timestamp: "2026-08-28 08:30 AM",
        description: "Assigned to Ramesh Sharma (W-041). Awaiting acceptance.",
      },
    ],
    amount: {
      base: 450,
      serviceFee: 45,
      gst: 89,
      total: 584,
    },
  },
  {
    id: "REQ-0988",
    consumerId: "cons-3",
    consumerName: "Kavita Shah",
    consumerPhone: "+91 99000 88776",
    categoryId: "carpentry",
    categoryName: "Carpentry",
    title: "Bedroom wardrobe hinge repair",
    problemDescription: "Replaced broken hinges on master bedroom wardrobe door and aligned latches.",
    preferredDate: "2026-08-27",
    preferredTimeSlot: "Morning (8am – 12pm)",
    address: {
      houseNo: "A-501, Sunrise Towers",
      locality: "Borivali East",
      pinCode: "400066",
      city: "Mumbai",
    },
    status: "PAID",
    assignedWorkerId: "worker-3",
    assignedWorkerName: "Anil Kamble",
    createdAt: "2026-08-27 09:00 AM",
    timeline: [
      { status: "REQUESTED", label: "Request Submitted", timestamp: "2026-08-27 09:00 AM" },
      { status: "WORKER_ACCEPTED", label: "Worker Accepted", timestamp: "2026-08-27 09:45 AM" },
      { status: "IN_PROGRESS", label: "Work Started", timestamp: "2026-08-27 10:30 AM" },
      { status: "COMPLETED", label: "Service Completed", timestamp: "2026-08-27 11:45 AM" },
      { status: "PAID", label: "Payment Confirmed", timestamp: "2026-08-27 12:00 PM" },
    ],
    completionNotes: "Replaced 4 soft-close hinges on wardrobe door and lubricated latches.",
    amount: {
      base: 600,
      serviceFee: 60,
      gst: 118,
      total: 778,
    },
    paymentStatus: "SUCCESS",
    rating: {
      stars: 5,
      review: "Very polite, fixed the door quickly and neatly!",
    },
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "audit-1",
    timestamp: "2026-08-28 08:30 AM",
    action: "ASSIGN_WORKER",
    actorRole: "COOPERATIVE_ADMIN",
    actorName: "Admin Sharma",
    details: "Assigned Ramesh Sharma (W-041) to Request REQ-1002",
  },
];
