import {
  ServiceCategory,
  WorkerProfile,
  ServiceRequest,
  AuditLog,
} from "../types";

export const INITIAL_CATEGORIES: ServiceCategory[] = [
  {
    id: "plumbing",
    name: "Plumbing Repairs",
    hindiName: "नल-प्लंबिंग सेवा",
    iconName: "Wrench",
    description: "Fix leaks, pipe installations, bathroom fitting repairs, and drainage unclogging by certified plumbers.",
    subServices: ["Pipe Leak Repair", "Tap Installation", "P-Trap Replacement", "Drain Unclogging"],
    basePrice: 350,
  },
  {
    id: "electrical",
    name: "Electrical Wiring & Appliances",
    hindiName: "बिजली और उपकरण",
    iconName: "Zap",
    description: "Circuit breaker fixes, ceiling fan installation, short circuit diagnosis, and safety inspections.",
    subServices: ["Fan Installation", "MCB Tripping Fix", "Switchboard Repair", "Wiring Inspection"],
    basePrice: 400,
  },
  {
    id: "cleaning",
    name: "Deep House Cleaning",
    hindiName: "घर की गहरी सफाई",
    iconName: "Sparkles",
    description: "Full house deep cleaning, bathroom sanitation, kitchen degreasing, and sofa shampooing.",
    subServices: ["2BHK Deep Clean", "Kitchen Sanitation", "Bathroom Scrubbing", "Sofa Shampooing"],
    basePrice: 800,
  },
  {
    id: "painting",
    name: "Wall Painting & Touch-up",
    hindiName: "दीवार पुताई व पेंट",
    iconName: "Paintbrush",
    description: "Interior wall touch-ups, waterproof coating, dampness treatment, and full room painting.",
    subServices: ["Wall Touch-up", "Dampness Treatment", "Waterproof Paint", "Color Coating"],
    basePrice: 600,
  },
  {
    id: "carpentry",
    name: "Furniture Repair & Carpentry",
    hindiName: "बढ़ईगीरी व फर्नीचर",
    iconName: "Hammer",
    description: "Door hinge alignment, cabinet repairs, custom wood fitting, and lock installations.",
    subServices: ["Hinge Alignment", "Cabinet Repair", "Lock Installation", "Wood Polishing"],
    basePrice: 450,
  },
];

export const INITIAL_WORKERS: WorkerProfile[] = [
  {
    id: "worker-1",
    workerCode: "W-042",
    name: "Suresh Kumar",
    phone: "+91 98201 12345",
    societyName: "Shivaji Labour Cooperative Society",
    rating: 4.6,
    jobsCompleted: 142,
    skills: ["Plumbing", "Pipe Repair"],
    serviceAreas: ["Thane", "Kalwa", "Majiwada"],
    status: "AVAILABLE",
    availableNow: true,
  },
  {
    id: "worker-2",
    workerCode: "W-041",
    name: "Amit Sharma",
    phone: "+91 98200 11223",
    societyName: "Shivaji Labour Cooperative Society",
    rating: 4.8,
    jobsCompleted: 18,
    skills: ["Plumbing", "Sanitation"],
    serviceAreas: ["Borivali East", "Kandivali West"],
    status: "AVAILABLE",
    availableNow: true,
  },
  {
    id: "worker-3",
    workerCode: "W-043",
    name: "Ramesh Patil",
    phone: "+91 98202 33445",
    societyName: "Dharavi Skilled Workers Federation",
    rating: 4.7,
    jobsCompleted: 12,
    skills: ["Electrical", "Wiring"],
    serviceAreas: ["Kalwa", "Thane West"],
    status: "BUSY",
    availableNow: false,
  },
  {
    id: "worker-4",
    workerCode: "W-044",
    name: "Vijay Kumar",
    phone: "+91 98203 44556",
    societyName: "Shivaji Labour Cooperative Society",
    rating: 4.5,
    jobsCompleted: 6,
    skills: ["Painting", "Coatings"],
    serviceAreas: ["Panch Pakhadi", "Thane"],
    status: "AVAILABLE",
    availableNow: true,
  },
];

export const INITIAL_REQUESTS: ServiceRequest[] = [
  {
    id: "1042",
    categoryId: "plumbing",
    categoryName: "Plumbing Repairs",
    title: "Pipe leakage repair",
    problemDescription: "Bathroom pipe is leaking near the sink. Water is pooling on the floor — would like it looked at today if possible.",
    consumerName: "Rahul Sharma",
    consumerPhone: "+91 98199 88776",
    address: {
      houseNo: "Flat 402, Building A",
      locality: "Thane",
      city: "Thane",
      pinCode: "400601",
    },
    status: "IN_PROGRESS",
    assignedWorkerId: "worker-1",
    assignedWorkerName: "Suresh Kumar",
    preferredDate: "2026-08-28",
    preferredTimeSlot: "10:00 AM",
    amount: {
      base: 350,
      fee: 50,
      tax: 72,
      total: 472,
    },
    createdAt: "2026-08-28T09:41:00Z",
  },
  {
    id: "1043",
    categoryId: "electrical",
    categoryName: "Electrical Wiring & Appliances",
    title: "Ceiling fan installation",
    problemDescription: "New ceiling fan needs to be mounted and wired in the living room.",
    consumerName: "Priya Verma",
    consumerPhone: "+91 98200 99887",
    address: {
      houseNo: "Flat 101, B Wing",
      locality: "Kalwa",
      city: "Thane",
      pinCode: "400605",
    },
    status: "WORKER_ASSIGNED",
    assignedWorkerId: "worker-3",
    assignedWorkerName: "Ramesh Patil",
    preferredDate: "2026-08-28",
    preferredTimeSlot: "11:00 AM",
    amount: {
      base: 400,
      fee: 50,
      tax: 81,
      total: 531,
    },
    createdAt: "2026-08-28T09:52:00Z",
  },
  {
    id: "1039",
    categoryId: "cleaning",
    categoryName: "Deep House Cleaning",
    title: "2BHK Full Deep Cleaning",
    problemDescription: "Deep clean 2BHK flat before festival event.",
    consumerName: "Amitabh Roy",
    consumerPhone: "+91 98201 22334",
    address: {
      houseNo: "Flat 503, Tower 2",
      locality: "Majiwada",
      city: "Thane",
      pinCode: "400601",
    },
    status: "WORKER_ACCEPTED",
    assignedWorkerId: "worker-5",
    preferredDate: "2026-08-28",
    preferredTimeSlot: "9:00 AM",
    amount: {
      base: 800,
      fee: 50,
      tax: 153,
      total: 1003,
    },
    createdAt: "2026-08-28T08:30:00Z",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "LOG-001",
    action: "ASSIGN_WORKER",
    actorName: "Meera Kulkarni",
    actorRole: "COOPERATIVE_ADMIN",
    details: "Assigned Suresh Kumar (W-042) to request #1042",
    timestamp: "2026-08-28T09:52:00Z",
  },
];
